[package]
name = "libbit-upload-pack"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["io-std", "io-util", "macros", "rt-multi-thread"] }
anyhow = "1"
libbit = { path = "../libbit" }