[package]
name = "bit-upload-pack"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
libbit = { path = "../libbit" }
tokio = { version = "1", features = ["io-std"] }

