[package]
name = "libbit"
version = "0.1.0"
authors = ["Andy Yu <andyyu2004@gmail.com>"]
edition = "2018"

[dependencies]
rust-ini = "0.16"
thiserror = "1.0"
flate2 = "1.0.20"
clap = "3.0.0-beta.2"
sha2 = "0.9.3"

[dev-dependencies]
tempfile = "3"

